site:
  title: Couchbase Documentation Style Guide
  url: https://labs.couchbase.com/docs-tooling
content:
  sources:
  - url: .
    branches: HEAD
    start_path: styleguidepages
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable 
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
output: 
  clean: true
  dir: ./docs
