= Examples

Add code examples where possible to show users how to work with Couchbase products. 

When adding a code sample: 

Do:: Make it relevant and applicable to your explanation. Make sure it is a working code sample that the user could use in their own projects. 
Don't:: Include cultural references. 

== Introducing Examples 

Use the following guidelines for adding an example into your documentation: 

* Don't use directional language to describe where in the text your example is, like "above" or "below." Use "preceding," "previous," or "following."

* Similar to xref:links.adoc[links], use "see."

* Use a colon at the end of the phrase you use to introduce your example. 

|===
| Acceptable | Not Acceptable

| See the following example: 
| See the example below.

a| For an example of how to use a `SELECT` query, see the following:

The following example shows how to use a `SELECT` query:
| The example below shows how to use a `SELECT` query.

|===

== Explaining Code Examples

Try to avoid the https://docs.couchbase.com/home/contribute/code-blocks.html#callouts[built-in code callouts] in Antora, where possible. 

Use small code examples with the explanation in regular text around the example. Add one-line code comments where appropriate to explain the assumptions made in a code example. Let the user know they should remove the comments to use the code in a production environment.

When you need to explain a larger code example: 

. Show the full example and provide a brief explanation. 
. Create a smaller code example out of the larger block of code. 
. Provide a more detailed explanation for the smaller code example. 
. Repeat Steps 2 and 3 until you've explained the code. 