name: Hakim testing

on:
  workflow_dispatch:
    inputs:

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
     
      - name: vale thing
        uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@master
