name: Hakim testing

on:
  workflow_dispatch:

jobs:
  vale:
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@main
    with:
      repo: ${{github.repository}}
      path: example
