name: Hakim testing

on:
  pull_request:
    types: [review_requested]
    paths: 
      # the following should match `path:` declaration below
      - example/**

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: reviewer
        run: |
          echo REVIEWER $REVIEWER
        env:
          REVIEWER: ${{ github.event.requested_reviewer.name }}

  vale:
    if: github.event.requested_reviewer.name == 'tech-comm-team-couchbase'
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@main
    with:
      path: example
      pull_request_number: ${{ github.event.number }}
      base_sha: ${{ github.event.pull_request.base.sha }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      repository: ${{ github.repository }}
    secrets: inherit
