name: Hakim testing2

on:
  workflow_dispatch:

jobs:
  no-inherit:
    uses: couchbaselabs/docs-runner/.github/workflows/secret-test@main

  inherit:
    uses: couchbaselabs/docs-runner/.github/workflows/secret-test@main
    secrets: inherit
