name: Hakim testing

on:
  workflow_dispatch:

env:
  CHECKOUT_PATH: example

jobs:
  vale:
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@main
    with:
      repo: ${{github.repository}}
      path: ${{github.env.CHECKOUT_PATH}}
