name: Hakim testing

on:
  workflow_dispatch:
    inputs:

jobs:
  checkout:
    uses: actions/checkout@v4

  vale:
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@master
    needs: checkout
