name: Hakim testing

on:
  workflow_dispatch:

env:
  PATH: example

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  vale:
    uses: couchbaselabs/docs-runner/.github/workflows/vale-review.yml@main
    needs: checkout
    with:
      path: ${{vars.PATH}}
